### PR TITLE
update to neo-node 3.6.2 and neo-modules 3.6.3

### LINKED ISSUE #30: [Neo v3.6.2] Add `MaxRequestBodySize` to `rpcserver.config`
See https://github.com/neo-project/neo-modules/pull/827

### PR DESCRIPTION
**Pull request by mialbu**
Closes #30

### CODE REVIEW

**Comment by mialbu** [comment]
@gsmachado fyi, I've committed the submodule neo-modules to the tag 3.6.3, since it's a hotfix release for 3.6.2 and should belong to the 3.6.2 release.

**Comment by gsmachado** [comment]
> @gsmachado fyi, I've committed the submodule neo-modules to the tag 3.6.3, since it's a hotfix release for 3.6.2 and should belong to the 3.6.2 release.

Alright! Thanks.

**Comment by gsmachado** [comment]
@mialbu @csmuller let's use the PR title specifying the neo-node and neo-modules versions.

I follow this pattern for a while already:
https://github.com/AxLabs/neo3-privatenet-docker/pulls?q=is%3Apr+is%3Aclosed

**Review by gsmachado — APPROVED** [review]
All fine. 💪

**Pull request merged**
